default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  sslmode: require

test:
  <<: *default
  database: animatch_test
  host: localhost
  username: <%= ENV.fetch("DB_USERNAME", ENV["USER"]) %>
  password: <%= ENV["DB_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  sslmode: require